#!/usr/bin/with-contenv sh

# Create configuration files from templates
if [ -f /opt/telegram-send/receiver.conf.j2 ];then
    j2 -o /opt/telegram-send/receiver.conf /opt/telegram-send/receiver.conf.j2
    rm /opt/telegram-send/receiver.conf.j2
fi
